name: go ci/cd

on:
    push:
        branches:
        - main
permissions:
    contents: read
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3

        - name: Setup Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.21.*'

        - name: Install dependencies
          run: |
            go version
            go get -u golang.org/x/lint/golint
        
        - name: Run build
          run: go build .

        - name: golangci-lint
          uses: golangci/golangci-lint-action@v3
          with:
            version: v1.54

            
    release:
          name: Create release
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Create Release
              id: create_release
              uses: actions/create-release@v1
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: Release ${{ github.ref }}
                body: |
                  Changes in this release
                  - First Change
                  - Second Change
                draft: false
                prerelease: false

        
            
