name: release

on:
    push:
        branches:
        - main
        tags:
        - v*

permissions:
    contents: write

jobs:
    build:
      name: Create Release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
          with:
            fetch-depth: 0
        
        - name: 'Get previous tag'
          id: previoustag
          uses: "WyriHaximus/github-action-get-previous-tag@v1"
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: 'Get next minor version'
          id: semver
          uses: "WyriHaximus/github-action-next-semvers@v1"
          with:
            version: ${{ steps.previoustag.outputs.tag }}
        
        - name: 'Create release'
          id: create_release
          uses: actions/create-release@v1
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: ${{ github.run_number }}
            release_name: ${{ steps.semver.outputs.patch }}
            draft: false
            prerelease: false